version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_production:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: nastysmit/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_production:/app/media/
  frontend:
    image: nastysmit/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: nastysmit/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/static
      - media_production:/app/media/
    ports:
      - 9000:80
